import mongoose from 'mongoose';

export const CANDIDATE_HISTORY_ACTIONS = [
  'CANDIDATE_APPLIED',
  'APPLICATION_CONFIRMATION_SENT',
  'APPLICATION_CONFIRMATION_FAILED',
  'RESUME_PARSE_STARTED',
  'RESUME_PARSED',
  'RESUME_PARSE_FAILED',
  'RESUME_REPROCESS_REQUESTED',
  'ATS_PROCESSED',
  'ATS_REPROCESSED',
  'CANDIDATE_ASSIGNMENT_UPDATED',
  'CANDIDATE_EMAIL_SENT',
  'INTERVIEW_SCHEDULED',
  'INTERVIEW_RESCHEDULED',
  'INTERVIEW_CANCELLED',
  'INTERVIEW_STARTED',
  'INTERVIEW_COMPLETED',
  'INTERVIEW_NO_SHOW',
  'INTERVIEW_FEEDBACK_SUBMITTED',
  'FINAL_REVIEW_STARTED',
  'CANDIDATE_SELECTED',
  'CANDIDATE_REJECTED',
  'CANDIDATE_HOLD',
  'OFFER_DRAFT_CREATED',
  'OFFER_UPDATED',
  'OFFER_SUBMITTED',
  'OFFER_APPROVED',
  'OFFER_APPROVAL_INVALIDATED',
  'OFFER_RETURNED',
  'OFFER_SEND_FAILED',
  'OFFER_SENT',
  'OFFER_VIEWED',
  'OFFER_ACCEPTED',
  'OFFER_REJECTED',
  'OFFER_EXPIRED',
  'OFFER_WITHDRAWN',
  'PRE_ONBOARDING_STARTED',
  'DOCUMENT_REQUESTED',
  'DOCUMENT_UPLOADED',
  'DOCUMENT_RESUBMITTED',
  'DOCUMENT_UNDER_REVIEW',
  'DOCUMENT_VERIFIED',
  'DOCUMENT_REJECTED',
  'DOCUMENT_RESUBMISSION_REQUIRED',
  'PRE_ONBOARDING_COMPLETED',
  'READY_TO_JOIN',
  'CANDIDATE_CONVERSION_STARTED',
  'CANDIDATE_CONVERTED',
  'EMPLOYEE_CREATED',
  'ACCOUNT_SETUP_SENT',
  'ACCOUNT_SETUP_COMPLETED',
  'ONBOARDING_STARTED',
  'CANDIDATE_JOINED',
  'BGV_STARTED',
  'BGV_INFORMATION_REQUESTED',
  'BGV_REVIEW_REQUIRED',
  'BGV_COMPLETED',
  // Phase 30.1 — optional BGV decision timeline events.
  'BGV_DECISION_WAIVED',
  'BGV_DECISION_INITIATED',
];

const candidateHistorySchema = new mongoose.Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company',
      required: true,
      index: true,
    },
    candidate: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Candidate',
      required: true,
      index: true,
    },
    job: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'JobPosting',
      required: true,
      index: true,
    },
    action: {
      type: String,
      enum: CANDIDATE_HISTORY_ACTIONS,
      required: true,
    },
    source: {
      type: String,
      enum: [
        'CAREER_PAGE',
        'INTERNAL',
        'RESUME_PARSER',
        'ATS_ENGINE',
        'PIPELINE',
        'INTERVIEW',
        'FINAL_DECISION',
        'OFFER',
        'PRE_ONBOARDING',
        'BGV_DECISION',
      ],
      default: 'CAREER_PAGE',
    },
    actorType: {
      type: String,
      enum: ['PUBLIC_CANDIDATE', 'TENANT_USER', 'SYSTEM'],
      default: 'SYSTEM',
    },
    actor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    eventAt: {
      type: Date,
      default: Date.now,
      index: true,
    },
  },
  { timestamps: true, versionKey: false }
);

candidateHistorySchema.index({ companyId: 1, candidate: 1, eventAt: -1 });

export default mongoose.model('CandidateHistory', candidateHistorySchema);
