// ============================================================
//  PHASE 30.1.1 · migratePhase30BgvPermissions.js
//
//  REVOKES the tenant-side BGV verifier permissions drafted in
//  Phase 30.1. Verification EXECUTION is Crewly-platform only
//  (BGV_TEAM / bgv:* platform perms under /api/super-admin/bgv);
//  tenants keep the 27.15 BACKGROUND_VERIFICATION_* permissions.
//
//  What it does (all atomic, all idempotent):
//    1. Resolve the six retired Permission DOCS by name (company
//       roles store Permission ObjectIds, not strings).
//    2. $pull those ids from EVERY CompanyRole (system + custom) —
//       one updateMany per permission, never a read-modify-write.
//    3. Deactivate the orphaned Permission rows (isActive=false —
//       kept for audit referential history, gone from every picker).
//
//  The BGV_VERIFIER role TEMPLATE needs no DB step: templates are a
//  static catalog (src/utils/roleTemplates.js) and the block is
//  already removed in code. Roles a company created FROM it are
//  cleaned by step 2.
//
//  SYSTEM_PERMISSION_VERSION moves 27 → 28 in permissionService so
//  system-role migrations converge once; the migration ADDS missing
//  defaults but never LOWERS roles, so this script is the removal
//  path (and the registry no longer lists the BGV family, so nothing
//  can re-grant it).
//
//  PowerShell, from the repo root:
//    cd Backend
//    npm run migrate:bgv30 -- --dry-run    # preview
//    npm run migrate:bgv30                 # apply
// ============================================================

import '../src/config/env.js';
import mongoose from 'mongoose';
import CompanyRole from '../src/models/CompanyRole.js';
import Permission from '../src/models/Permission.js';

const DRY = process.argv.includes('--dry-run');

// Permission names as generated by utils/permissionRegistry.js
// (`${RESOURCE}_${ACTION}`). Hard-coded on purpose: the registry no
// longer defines the BGV company family, so the script must not
// import them from it.
const REVOKED_NAMES = [
  'BGV_CHECK_READ',
  'BGV_CHECK_ASSIGN',
  'BGV_CHECK_VERIFY',
  'BGV_CHECK_MANAGE',
  'BGV_CHECK_OVERRIDE',
  'BGV_EVIDENCE_MANAGE',
];

const main = async () => {
  const uri = process.env.MONGO_URI;
  if (!uri) throw new Error('MONGO_URI missing — set it in Backend/.env');
  await mongoose.connect(uri);

  // 1) resolve retired permission rows (by name; any isActive state)
  const revoked = await Permission.find({ name: { $in: REVOKED_NAMES } })
    .select('_id name isActive')
    .lean();
  console.log(`Retired BGV permissions present in DB: ${revoked.length}/${REVOKED_NAMES.length}`);
  for (const permission of revoked) {
    console.log(`  ${permission.name}${permission.isActive ? '' : ' (already inactive)'}`);
  }
  const missing = REVOKED_NAMES.filter((name) => !revoked.some((p) => p.name === name));
  if (missing.length) console.log(`Never-seeded (nothing to revoke): ${missing.join(', ')}`);

  if (revoked.length) {
    const ids = revoked.map((permission) => permission._id);

    // 2) atomic $pull from every tenant role that still holds one
    let rolesAffected = 0;
    for (const id of ids) {
      const result = DRY
        ? { modifiedCount: await CompanyRole.countDocuments({ permissions: id }) }
        : await CompanyRole.updateMany({ permissions: id }, { $pull: { permissions: id } });
      rolesAffected += result.modifiedCount || 0;
      console.log(`  role rows touched: ${result.modifiedCount || 0}`);
    }
    console.log(`CompanyRole revocations: ${rolesAffected} role-update(s)`);

    const emptied = DRY ? -1 : await CompanyRole.countDocuments({ isSystemRole: false, permissions: { $size: 0 } });
    if (emptied >= 0) console.log(`Custom roles now with NO permissions: ${emptied} (company admin may prune them)`);

    // 3) deactivate the permission rows so the picker catalog is clean
    if (!DRY) {
      await Permission.updateMany({ _id: { $in: ids } }, { $set: { isActive: false } });
    }
  }

  console.log(DRY
    ? 'DRY RUN — no changes written.'
    : 'Done. Tenant roles hold no verifier permissions; retired rows deactivated.');
  await mongoose.disconnect();
};

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
